# Generated by Django 5.2.6 on 2025-09-29 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_page_tinymcemedia'),
        ('users', '0002_user_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.CharField(blank=True, help_text='视频作者', max_length=200, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='media',
            name='collection_volume',
            field=models.IntegerField(default=0, help_text='视频收藏量', verbose_name='收藏量'),
        ),
        migrations.AddField(
            model_name='media',
            name='comments_count',
            field=models.IntegerField(default=0, help_text='视频评论数量', verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='media',
            name='favorites',
            field=models.IntegerField(default=0, help_text='视频收藏数量', verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='media',
            name='heat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='视频热度值', max_digits=10, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='media',
            name='md5_hash',
            field=models.CharField(blank=True, help_text='视频文件MD5哈希值，用于去重', max_length=32, verbose_name='视频MD5哈希'),
        ),
        migrations.AddField(
            model_name='media',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='视频原始发布日期', null=True, verbose_name='发布日期'),
        ),
        migrations.AddField(
            model_name='media',
            name='rank_date',
            field=models.DateField(blank=True, help_text='视频上榜日期', null=True, verbose_name='排行榜日期'),
        ),
        migrations.AddField(
            model_name='media',
            name='rank_position',
            field=models.IntegerField(default=0, help_text='在排行榜中的位置', verbose_name='排名位置'),
        ),
        migrations.AddField(
            model_name='media',
            name='rank_type',
            field=models.CharField(blank=True, choices=[('daily', '日榜'), ('weekly', '周榜'), ('monthly', '月榜')], help_text='视频所属排行榜类型', max_length=20, verbose_name='排行榜类型'),
        ),
        migrations.AddField(
            model_name='media',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='视频评分', max_digits=5, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='media',
            name='viewkey',
            field=models.CharField(blank=True, help_text='91porn网站的唯一标识符', max_length=100, unique=True, verbose_name='91porn唯一标识'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['rank_type', 'rank_date'], name='files_media_rank_ty_29f5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['viewkey'], name='files_media_viewkey_6670a2_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['heat'], name='files_media_heat_f85cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['score'], name='files_media_score_d24fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['rank_position'], name='files_media_rank_po_e66d51_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['author'], name='files_media_author_63f710_idx'),
        ),
    ]
